### ISSUE TITLE
Image retrieved but not displayed

### ISSUE THREAD

**Issue by codehimanshu** [codehimanshu/handle-image#1]
![capture](https://cloud.githubusercontent.com/assets/14791631/15762830/9c6e8be8-293d-11e6-8b60-c19fe1e68e91.PNG)
`echo "<img src='get.php?id=$id' height=200px>";`
image opens on opening image in new tab but does not appear at main page.
@shashaa35 sir pls check

**Comment by shashaa35** [comment]
When you click on image " get.php"  executes..
Till then get.php doesn't executes, so I age doesn't loads..

**Comment by shashaa35** [comment]
First of all,move the php script of your index.php file into a new file, because it is executing every time the page loads.Call it through form action.
And second - you put "get.php/$id" in img src,it is a call to a php file and you want to execute it through image tag..which is not possible .
Get.php displays image itself,that means you are trying something like this in your index.php file..
<img src="<img src="zxc.jpg">"> 
This is the reason you are able to see the image in new tab because when you click on it shows its source which is itself a image.

Just call the script one time when user clicks on upload button..
and in that script you should display image..
But remember that will make you directed to next page.
If you want to stay on the same page and do all these things you should use AJAX..

**Comment by codehimanshu** [comment]
Thanks for help sir. Problem solved.
